"""Add show_inline and display_order to FieldRegistry

Revision ID: 088ba4422676
Revises: be7900d9847e
Create Date: 2025-07-12 20:49:39.937568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088ba4422676'
down_revision: Union[str, None] = 'be7900d9847e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_registry', sa.Column('show_inline', sa.Boolean(), nullable=True))
    op.add_column('field_registry', sa.Column('display_order', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_registry', 'display_order')
    op.drop_column('field_registry', 'show_inline')
    # ### end Alembic commands ###
