"""add profile pic

Revision ID: 21fa94f79d22
Revises: 266f625b54f9
Create Date: 2025-08-03 19:50:36.847751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fa94f79d22'
down_revision: Union[str, None] = '266f625b54f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('profile_attachment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'animals', 'attachments', ['profile_attachment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.drop_column('animals', 'profile_attachment_id')
    # ### end Alembic commands ###
