"""add field registry optionality

Revision ID: 326719b37b34
Revises: 5c04a4d20f0b
Create Date: 2025-07-09 19:11:46.211129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326719b37b34'
down_revision: Union[str, None] = '5c04a4d20f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_registry', sa.Column('optional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_registry', 'optional')
    # ### end Alembic commands ###
