"""add medical

Revision ID: 34ce8d82bde4
Revises: ce98b75b094c
Create Date: 2025-07-26 21:01:20.775162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ce8d82bde4'
down_revision: Union[str, None] = 'ce98b75b094c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_name', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('paid', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_events_created_on'), 'medical_events', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_events_created_on'), table_name='medical_events')
    op.drop_table('medical_events')
    # ### end Alembic commands ###
