"""add visibility level

Revision ID: 471df477e61c
Revises: 326719b37b34
Create Date: 2025-07-09 20:35:30.711302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471df477e61c'
down_revision: Union[str, None] = '326719b37b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_registry', sa.Column('visibility_level', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_registry', 'visibility_level')
    # ### end Alembic commands ###
