"""add field registry

Revision ID: 5c04a4d20f0b
Revises: f46862514135
Create Date: 2025-07-09 18:47:14.932711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c04a4d20f0b'
down_revision: Union[str, None] = 'f46862514135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('globally_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'field_name', name='uq_model_field')
    )
    op.drop_table('visible_fields')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('visible_fields',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('field_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('label', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('field_registry')
    # ### end Alembic commands ###
