"""at to on

Revision ID: 8c89410d4e41
Revises: 35580c9c7eac
Create Date: 2025-07-10 10:39:10.340836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from click.core import batch
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c89410d4e41'
down_revision: Union[str, None] = '35580c9c7eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals') as batch_op:
        batch_op.alter_column('created_at', new_column_name='created_on', existing_type=sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
        batch_op.alter_column('updated_at', new_column_name='updated_on', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('died_at', new_column_name='died_on', existing_type=sa.Date(), existing_nullable=True)

    with op.batch_alter_table('guests') as batch_op:
        batch_op.alter_column('created_at', new_column_name='created_on', existing_type=sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
        batch_op.alter_column('changed_at', new_column_name='updated_on', existing_type=sa.Date(), nullable=False)

    with op.batch_alter_table('payments') as batch_op:
        batch_op.alter_column('created_at', new_column_name='created_on', existing_type=sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments') as batch_op:
        batch_op.alter_column('created_on', new_column_name='created_at', existing_type=sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)

    with op.batch_alter_table('guests') as batch_op:
        batch_op.alter_column('created_on', new_column_name='created_at', existing_type=sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
        batch_op.alter_column('updated_on', new_column_name='changed_at', existing_type=sa.Date(), nullable=False)

    with op.batch_alter_table('animals') as batch_op:
        batch_op.alter_column('created_on', new_column_name='created_at', existing_type=sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False)
        batch_op.alter_column('updated_on', new_column_name='updated_at', existing_type=sa.Date(), nullable=False)
        batch_op.alter_column('died_on', new_column_name='died_at', existing_type=sa.Date(), existing_nullable=True)
    # ### end Alembic commands ###
