"""empty message

Revision ID: b5f198fa3046
Revises: 9c3f0c6d2c44
Create Date: 2025-12-14 22:52:58.742913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5f198fa3046'
down_revision: Union[str, None] = '9c3f0c6d2c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_dispense_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_food_plan_created_by'),
    sa.ForeignKeyConstraint(['location_id'], ['drop_off_locations.id'], name='fk_food_plan_location'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_dispense_plans_location_id'), 'food_dispense_plans', ['location_id'], unique=False)
    op.create_index(op.f('ix_food_dispense_plans_plan_date'), 'food_dispense_plans', ['plan_date'], unique=False)
    op.drop_index('ix_medical_events_created_on', table_name='medical_events')
    op.drop_table('medical_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_events',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('vet_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_on', sa.DATE(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('costs', mysql.FLOAT(), nullable=True),
    sa.Column('paid', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_medical_events_created_on', 'medical_events', ['created_on'], unique=False)
    op.drop_index(op.f('ix_food_dispense_plans_plan_date'), table_name='food_dispense_plans')
    op.drop_index(op.f('ix_food_dispense_plans_location_id'), table_name='food_dispense_plans')
    op.drop_table('food_dispense_plans')
    # ### end Alembic commands ###
