"""fix fk

Revision ID: bcee8060bd96
Revises: dc2f952881b9
Create Date: 2025-07-19 23:20:56.692421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcee8060bd96'
down_revision: Union[str, None] = 'dc2f952881b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('animals_ibfk_1', 'animals', type_='foreignkey')
    op.create_foreign_key('fk_animals_guest_id', 'animals', 'guests', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_animals_guest_id', 'animals', type_='foreignkey')
    op.create_foreign_key('animals_ibfk_1', 'animals', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
