"""add guest card date

Revision ID: be7900d9847e
Revises: 8c89410d4e41
Create Date: 2025-07-12 15:56:36.236208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7900d9847e'
down_revision: Union[str, None] = '8c89410d4e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('guest_card_printed_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'guest_card_printed_on')
    # ### end Alembic commands ###
