"""add attachements

Revision ID: c368e2c10dd5
Revises: 34ce8d82bde4
Create Date: 2025-07-26 21:03:21.716630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c368e2c10dd5'
down_revision: Union[str, None] = '34ce8d82bde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.Enum('guest', 'animal', 'payment', 'medical', name='attachment_types'), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('gcs_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_owner', 'attachments', ['owner_type', 'owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachments_owner', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
