"""add msg

Revision ID: ce98b75b094c
Revises: a5b8059567fa
Create Date: 2025-07-25 21:59:41.116893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce98b75b094c'
down_revision: Union[str, None] = 'a5b8059567fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('completed', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_message_user_id'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='fk_message_guest_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_on'), 'messages', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_on'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
