"""clean_up_3

Revision ID: d62e0f5947d3
Revises: b6a32da6a007
Create Date: 2025-07-09 17:36:37.274058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd62e0f5947d3'
down_revision: Union[str, None] = 'b6a32da6a007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_animals_guest_id', 'animals', type_='foreignkey')
    op.create_foreign_key('fk_animals_guest_id', 'animals', 'guests', ['guest_id'], ['id'])
    op.alter_column('changelog', 'guest_id',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    # op.drop_constraint('FK_changelog_guests', 'changelog', type_='foreignkey')
    # op.drop_constraint('changelog_ibfk_1', 'changelog', type_='foreignkey')
    # op.drop_index('gast_id', table_name='changelog')
    # op.create_index(op.f('ix_changelog_change_timestamp'), 'changelog', ['change_timestamp'], unique=False)
    # op.create_index(op.f('ix_changelog_guest_id'), 'changelog', ['guest_id'], unique=False)
    op.alter_column('food_history', 'guest_id',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    # op.create_index(op.f('ix_food_history_distributed_on'), 'food_history', ['distributed_on'], unique=False)
    # op.create_index(op.f('ix_food_history_guest_id'), 'food_history', ['guest_id'], unique=False)
    # op.drop_constraint('FK_food_guests', 'food_history', type_='foreignkey')
    # op.drop_index('gast_id', table_name='food_history')

    # op.create_foreign_key('fk_food_history_guest_id', 'food_history', 'guests', ['guest_id'], ['id'])
    op.alter_column('guests', 'number',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('guests', 'firstname',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('guests', 'lastname',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)

    op.alter_column('guests', 'member_since',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('guests', 'status',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text('1'))
    op.alter_column('guests', 'created_on',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('guests', 'updated_on',
                    existing_type=sa.DATE(),
                    nullable=False)
    # op.create_index(op.f('ix_guests_firstname'), 'guests', ['firstname'], unique=False)
    # op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    # op.create_index(op.f('ix_guests_lastname'), 'guests', ['lastname'], unique=False)
    # op.create_index(op.f('ix_guests_number'), 'guests', ['number'], unique=False)
    op.alter_column('payments', 'guest_id',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('payments', 'food_amount',
                    existing_type=mysql.FLOAT(),
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_nullable=True)
    op.alter_column('payments', 'other_amount',
                    existing_type=mysql.FLOAT(),
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_nullable=True)
    op.alter_column('payments', 'created_on',
                    existing_type=sa.DATE(),
                    type_=sa.DateTime(),
                    existing_nullable=True,
                    existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('payments', 'paid',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text('1'))
    # op.create_index(op.f('ix_payments_guest_id'), 'payments', ['guest_id'], unique=False)
    # op.create_index(op.f('ix_payments_paid_on'), 'payments', ['paid_on'], unique=False)
    # op.drop_constraint('FK_payment_guests', 'payments', type_='foreignkey')
    # op.drop_index('gast_id', table_name='payments')

    # op.create_foreign_key('fk_payments_guest_id', 'payments', 'guests', ['guest_id'], ['id'])
    op.alter_column('representative', 'phone',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    # op.create_index(op.f('ix_representative_guest_id'), 'representative', ['guest_id'], unique=False)
    op.alter_column('users', 'role',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('users', 'realname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'realname',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('representative', 'phone',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint('fk_payments_guest_id', 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_representative_guest_id'), table_name='representative')

    op.create_foreign_key('FK_payment_guests', 'payments', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_paid_on'), table_name='payments')
    op.drop_index(op.f('ix_payments_guest_id'), table_name='payments')
    op.create_index('gast_id', 'payments', ['guest_id'], unique=False)
    op.alter_column('payments', 'paid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('payments', 'other_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('payments', 'food_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('payments', 'guest_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_guests_number'), table_name='guests')
    op.drop_index(op.f('ix_guests_lastname'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_firstname'), table_name='guests')
    op.alter_column('guests', 'changed_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('guests', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('guests', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('guests', 'member_since',
               existing_type=sa.DATE(),
               nullable=True)

    op.alter_column('guests', 'lastname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('guests', 'firstname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('guests', 'number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('fk_food_history_guest_id', 'food_history', type_='foreignkey')
    op.create_foreign_key('FK_food_guests', 'food_history', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_food_history_guest_id'), table_name='food_history')
    op.drop_index(op.f('ix_food_history_distributed_on'), table_name='food_history')
    op.create_index('gast_id', 'food_history', ['guest_id'], unique=False)
    op.alter_column('food_history', 'guest_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('changelog', sa.Column('changed_by', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_changelog_guest_id'), table_name='changelog')
    op.drop_index(op.f('ix_changelog_change_timestamp'), table_name='changelog')
    op.create_index('gast_id', 'changelog', ['guest_id'], unique=False)
    op.create_foreign_key('changelog_ibfk_1', 'changelog', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')

    op.alter_column('changelog', 'guest_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('fk_animals_guest_id', 'animals', type_='foreignkey')
    op.create_foreign_key('fk_animals_guest_id', 'animals', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
