"""clean_up 4

Revision ID: d9d5662de244
Revises: d62e0f5947d3
Create Date: 2025-07-09 17:51:22.766776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9d5662de244'
down_revision: Union[str, None] = 'd62e0f5947d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_changelog_guest_id', 'changelog', 'guests', ['guest_id'], ['id'])

    op.drop_column('changelog', 'changed_by')
    op.drop_constraint('food_history_ibfk_1', 'food_history', type_='foreignkey')
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('payments_ibfk_1', 'payments', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('food_history_ibfk_1', 'food_history', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    op.add_column('changelog', sa.Column('changed_by', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint('fk_changelog_guest_id', 'changelog', type_='foreignkey')
    # ### end Alembic commands ###
