"""add backcascade

Revision ID: dc2f952881b9
Revises: 61246a5035cd
Create Date: 2025-07-17 22:38:43.803054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2f952881b9'
down_revision: Union[str, None] = '61246a5035cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_animals_guest_id', 'animals', type_='foreignkey')
    op.create_foreign_key(None, 'animals', 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.create_foreign_key('fk_animals_guest_id', 'animals', 'guests', ['guest_id'], ['id'])
    # ### end Alembic commands ###
