"""add ui label

Revision ID: e1f46d367a5d
Revises: 471df477e61c
Create Date: 2025-07-09 20:51:48.451769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f46d367a5d'
down_revision: Union[str, None] = '471df477e61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_registry', sa.Column('ui_label', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_registry', 'ui_label')
    # ### end Alembic commands ###
