"""add representative table and rename guests

Revision ID: e6fbf57cdeb7
Revises: 1a87c5ae1a4c
Create Date: 2025-07-07 15:22:20.045908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fbf57cdeb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # guest:
    op.rename_table("gaeste", "guests")

    op.add_column('guests', sa.Column('status_temp', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.execute("""
               UPDATE guests
               SET status_temp = CASE
                                     WHEN status = 'Aktiv' THEN TRUE
                                     WHEN status = 'Inaktiv' THEN FALSE
                                     ELSE FALSE
                   END
               """)
    op.add_column('guests', sa.Column('gender_temp', sa.Enum('male','female','other','unknown'), server_default='unknown'))

    op.execute("""
               UPDATE guests
               SET gender_temp = CASE
                                    WHEN geschlecht IN ('Männlich', 'Herr', 'M') THEN 'male'
                                    WHEN geschlecht IN ('Weiblich', 'Frau', 'W') THEN 'female'
                                    WHEN geschlecht IN ('Divers', 'd') THEN 'other'
                                    ELSE 'unknown'
                   END;""")

    # Rename columns to fix typos and improve naming consistency
    with op.batch_alter_table('guests') as batch_op:
        batch_op.alter_column('nummer', new_column_name='number', type_=sa.String(length=255))
        batch_op.alter_column('vorname', new_column_name='firstname', type_=sa.String(length=255))
        batch_op.alter_column('nachname', new_column_name='lastname', type_=sa.String(length=255))
        batch_op.alter_column('adresse', new_column_name='address', type_=sa.String(length=255))
        batch_op.alter_column('ort', new_column_name='city', type_=sa.String(length=255))
        batch_op.alter_column('plz', new_column_name='zip', type_=sa.String(length=255))
        batch_op.alter_column('festnetz', new_column_name='phone', type_=sa.String(length=255))
        batch_op.alter_column('mobil', new_column_name='mobile', type_=sa.String(length=255))
        batch_op.alter_column('geburtsdatum', new_column_name='birthdate', type_=sa.Date())
        batch_op.drop_column('geschlecht')
        batch_op.alter_column('gender_temp', new_column_name='gender', type_=sa.Enum('male','female','other','unknown', name='gender_enum'))
        batch_op.alter_column('eintritt', new_column_name='member_since', type_=sa.Date())
        batch_op.alter_column('austritt', new_column_name='member_until', type_=sa.Date())
        batch_op.drop_column('status')
        batch_op.alter_column('status_temp', new_column_name='status', type_=sa.Boolean(), nullable=False, server_default=sa.text('1'))
        batch_op.alter_column('beduerftigkeit', new_column_name='indigence', type_=sa.String(length=255))
        batch_op.alter_column('beduerftig_bis', new_column_name='indigent_until', type_=sa.Date())
        batch_op.alter_column('dokumente', new_column_name='documents', type_=sa.Text())
        batch_op.alter_column('notizen', new_column_name='notes', type_=sa.Text())
        batch_op.alter_column('erstellt_am', new_column_name='created_at', type_=sa.Date())
        batch_op.alter_column('aktualisiert_am', new_column_name='changed_at', type_=sa.Date())


    op.create_table('representative',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('name', sa.String(length=255), nullable=True),
                        sa.Column('phone', sa.String(length=50), nullable=True),
                        sa.Column('email', sa.String(length=255), nullable=True),
                        sa.Column('address', sa.String(length=255), nullable=True),
                        sa.Column('guest_id', sa.String(length=255), nullable=False),
                        sa.PrimaryKeyConstraint('id')
                        )

    # Migrate all vertreter_* data from guests to representative table
    op.execute("""
        INSERT INTO representative (name, phone, email, address, guest_id)
        SELECT vertreter_name, vertreter_telefon, vertreter_email, vertreter_adresse, id
        FROM guests
        WHERE vertreter_name IS NOT NULL OR vertreter_telefon IS NOT NULL OR vertreter_email IS NOT NULL OR vertreter_adresse IS NOT NULL
    """)
    with op.batch_alter_table('guests') as batch_op:
        batch_op.drop_column('vertreter_name')
        batch_op.drop_column('vertreter_telefon')
        batch_op.drop_column('vertreter_email')
        batch_op.drop_column('vertreter_adresse')


def downgrade() -> None:
    # Re-add vertreter columns to guests table
    with op.batch_alter_table('guests') as batch_op:
        batch_op.add_column(sa.Column('vertreter_adresse', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vertreter_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vertreter_telefon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vertreter_name', sa.String(length=255), nullable=True))

    # Copy data back from representative table to guests table
    op.execute("""
        UPDATE guests
        SET vertreter_name = (
                SELECT name FROM representative r WHERE r.guest_id = guests.id LIMIT 1
            ),
            vertreter_telefon = (
                SELECT phone FROM representative r WHERE r.guest_id = guests.id LIMIT 1
            ),
            vertreter_email = (
                SELECT email FROM representative r WHERE r.guest_id = guests.id LIMIT 1
            ),
            vertreter_adresse = (
                SELECT address FROM representative r WHERE r.guest_id = guests.id LIMIT 1
            )
        WHERE EXISTS (
            SELECT 1 FROM representative r WHERE r.guest_id = guests.id
        )
    """)

    # Drop representative table
    op.drop_table('representative')

    # Rename columns back to original names and undo type changes
    with op.batch_alter_table('guests') as batch_op:
        batch_op.alter_column('number', new_column_name='nummer', type_=sa.String(length=255))
        batch_op.alter_column('firstname', new_column_name='vorname', type_=sa.String(length=255))
        batch_op.alter_column('lastname', new_column_name='nachname', type_=sa.String(length=255))
        batch_op.alter_column('address', new_column_name='adresse', type_=sa.String(length=255))
        batch_op.alter_column('city', new_column_name='ort', type_=sa.String(length=255))
        batch_op.alter_column('zip', new_column_name='plz', type_=sa.String(length=255))
        batch_op.alter_column('phone', new_column_name='festnetz', type_=sa.String(length=50))
        batch_op.alter_column('mobile', new_column_name='mobil', type_=sa.String(length=50))
        batch_op.alter_column('birthdate', new_column_name='geburtsdatum', type_=sa.Date())
        batch_op.alter_column('gender', new_column_name='gender_temp', type_=sa.Enum('male','female','other','unknown', name='gender_enum'))
        batch_op.alter_column('member_since', new_column_name='eintritt', type_=sa.Date())
        batch_op.alter_column('member_until', new_column_name='austritt', type_=sa.Date())
        batch_op.alter_column('status', new_column_name='status_temp', type_=sa.Boolean())
        batch_op.add_column(sa.Column('status', sa.Enum('Aktiv', 'Inaktiv'), nullable=False, server_default='Aktiv'))
        batch_op.execute("""
            UPDATE guests
            SET status = CASE
                             WHEN status_temp = 1 THEN 'Aktiv'
                             ELSE 'Inaktiv'
                         END
        """)
        batch_op.drop_column('status_temp')
        batch_op.alter_column('indigence', new_column_name='beduerftigkeit', type_=sa.String(length=255))
        batch_op.alter_column('indigent_until', new_column_name='beduerftig_bis', type_=sa.Date())
        batch_op.alter_column('documents', new_column_name='dokumente', type_=sa.Text())
        batch_op.alter_column('notes', new_column_name='notizen', type_=sa.Text())
        batch_op.alter_column('created_at', new_column_name='erstellt_am', type_=sa.Date())
        batch_op.alter_column('changed_at', new_column_name='aktualisiert_am', type_=sa.Date())
    # Add temporary column to convert gender back to original enum
    op.add_column('guests', sa.Column('geschlecht', sa.Enum('Männlich', 'Weiblich', 'Divers', 'Unbekannt',
                                                            name='geschlecht_enum'), nullable=True))

    op.execute("""
        UPDATE guests
        SET geschlecht = CASE
                             WHEN gender = 'male' THEN 'Männlich'
                             WHEN gender = 'female' THEN 'Weiblich'
                             WHEN gender = 'other' THEN 'Divers'
                             WHEN gender = 'unknown' THEN 'Unbekannt'
                             ELSE NULL
                         END
    """)
    op.drop_column('guests', 'gender')
    op.execute('DROP TYPE IF EXISTS gender_enum')
    # Rename guests table back to gaeste
    op.rename_table("guests", "gaeste")
    op.execute('DROP TYPE IF EXISTS gender_enum')
