"""Add editability level to field registry

Revision ID: fda720b762c1
Revises: bcee8060bd96
Create Date: 2025-07-25 19:46:03.753421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda720b762c1'
down_revision: Union[str, None] = 'bcee8060bd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_registry', sa.Column('editability_level', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_registry', 'editable_level')
    # ### end Alembic commands ###
