"""Clean Up

Revision ID: ff2cac1d9c0d
Revises: cdf9e0e0a9cc
Create Date: 2025-07-09 17:00:28.822424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff2cac1d9c0d'
down_revision: Union[str, None] = 'cdf9e0e0a9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'guest_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('animals', 'breed',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('animals', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('animals', 'color',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('animals', 'identification',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('animals', 'weight_or_size',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('animals', 'created_at',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('animals', 'updated_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('animals', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))


    # ### end Alembic commands ###




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('animals', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('animals', 'updated_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('animals', 'created_at',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('animals', 'weight_or_size',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('animals', 'identification',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('animals', 'color',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('animals', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('animals', 'breed',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('animals', 'guest_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
